load('fig2.mat')

save('fig2.mat','proposedReward', 'proposedEnergyHarvest',...
    'energyReward', 'energyEnergyHarvest',...
    'randomReward', 'randomEnergyHarvest',...
    'myopicReward', 'myopicEnergyHarvest',...
    'CSMAoverallreward', 'CSMAenergyHarvested')